/*
 * pagarmecoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package invoices_pkg

import "time"
import "pagarmecoreapi_lib/configuration_pkg"
import "pagarmecoreapi_lib/models_pkg"

/*
 * Interface for the INVOICES_IMPL
 */
type INVOICES interface {
    GetPartialInvoice (string) (*models_pkg.GetInvoiceResponse, error)

    CancelInvoice (string, *string) (*models_pkg.GetInvoiceResponse, error)

    CreateInvoice (string, string, *models_pkg.CreateInvoiceRequest, *string) (*models_pkg.GetInvoiceResponse, error)

    UpdateInvoiceMetadata (string, *models_pkg.UpdateMetadataRequest, *string) (*models_pkg.GetInvoiceResponse, error)

    GetInvoices (*int64, *int64, *string, *string, *string, *time.Time, *time.Time, *string, *time.Time, *time.Time, *string) (*models_pkg.ListInvoicesResponse, error)

    GetInvoice (string) (*models_pkg.GetInvoiceResponse, error)

    UpdateInvoiceStatus (string, *models_pkg.UpdateInvoiceStatusRequest, *string) (*models_pkg.GetInvoiceResponse, error)
}

/*
 * Factory for the INVOICES interaface returning INVOICES_IMPL
 */
func NewINVOICES(config configuration_pkg.CONFIGURATION) *INVOICES_IMPL {
    client := new(INVOICES_IMPL)
    client.config = config
    return client
}