/*
 * pagarmecoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package orders_pkg

import "time"
import "pagarmecoreapi_lib/configuration_pkg"
import "pagarmecoreapi_lib/models_pkg"

/*
 * Interface for the ORDERS_IMPL
 */
type ORDERS interface {
    GetOrders (*int64, *int64, *string, *string, *time.Time, *time.Time, *string) (*models_pkg.ListOrderResponse, error)

    UpdateOrderItem (string, string, *models_pkg.UpdateOrderItemRequest, *string) (*models_pkg.GetOrderItemResponse, error)

    DeleteAllOrderItems (string, *string) (*models_pkg.GetOrderResponse, error)

    DeleteOrderItem (string, string, *string) (*models_pkg.GetOrderItemResponse, error)

    CloseOrder (string, *models_pkg.UpdateOrderStatusRequest, *string) (*models_pkg.GetOrderResponse, error)

    CreateOrder (*models_pkg.CreateOrderRequest, *string) (*models_pkg.GetOrderResponse, error)

    CreateOrderItem (string, *models_pkg.CreateOrderItemRequest, *string) (*models_pkg.GetOrderItemResponse, error)

    GetOrderItem (string, string) (*models_pkg.GetOrderItemResponse, error)

    UpdateOrderMetadata (string, *models_pkg.UpdateMetadataRequest, *string) (*models_pkg.GetOrderResponse, error)

    GetOrder (string) (*models_pkg.GetOrderResponse, error)
}

/*
 * Factory for the ORDERS interaface returning ORDERS_IMPL
 */
func NewORDERS(config configuration_pkg.CONFIGURATION) *ORDERS_IMPL {
    client := new(ORDERS_IMPL)
    client.config = config
    return client
}