/*
 * pagarmecoreapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package charges_pkg

import "time"
import "pagarmecoreapi_lib/configuration_pkg"
import "pagarmecoreapi_lib/models_pkg"

/*
 * Interface for the CHARGES_IMPL
 */
type CHARGES interface {
    UpdateChargeMetadata (string, *models_pkg.UpdateMetadataRequest, *string) (*models_pkg.GetChargeResponse, error)

    UpdateChargePaymentMethod (string, *models_pkg.UpdateChargePaymentMethodRequest, *string) (*models_pkg.GetChargeResponse, error)

    GetChargeTransactions (string, *int64, *int64) (*models_pkg.ListChargeTransactionsResponse, error)

    UpdateChargeDueDate (string, *models_pkg.UpdateChargeDueDateRequest, *string) (*models_pkg.GetChargeResponse, error)

    GetCharges (*int64, *int64, *string, *string, *string, *string, *string, *time.Time, *time.Time) (*models_pkg.ListChargesResponse, error)

    CaptureCharge (string, *models_pkg.CreateCaptureChargeRequest, *string) (*models_pkg.GetChargeResponse, error)

    UpdateChargeCard (string, *models_pkg.UpdateChargeCardRequest, *string) (*models_pkg.GetChargeResponse, error)

    GetCharge (string) (*models_pkg.GetChargeResponse, error)

    GetChargesSummary (string, *time.Time, *time.Time) (*models_pkg.GetChargesSummaryResponse, error)

    RetryCharge (string, *string) (*models_pkg.GetChargeResponse, error)

    CancelCharge (string, *models_pkg.CreateCancelChargeRequest, *string) (*models_pkg.GetChargeResponse, error)

    CreateCharge (*models_pkg.CreateChargeRequest, *string) (*models_pkg.GetChargeResponse, error)

    ConfirmPayment (string, *models_pkg.CreateConfirmPaymentRequest, *string) (*models_pkg.GetChargeResponse, error)
}

/*
 * Factory for the CHARGES interaface returning CHARGES_IMPL
 */
func NewCHARGES(config configuration_pkg.CONFIGURATION) *CHARGES_IMPL {
    client := new(CHARGES_IMPL)
    client.config = config
    return client
}